'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18046
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18046.
'
Namespace dynamicAgapeConnect
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DatatSyncSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DatatSync
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestAPBalancesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetAPBalancesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSuggestedPaymentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RequestUpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestRequestUpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateResponsesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RequestUpdateWithAccountRefreshOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SolomonInterface.My.MySettings.Default.SolomonInterface_dynamicAgapeConnect_DatatSync
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event TestAPBalancesCompleted As TestAPBalancesCompletedEventHandler
        
        '''<remarks/>
        Public Event SetAPBalancesCompleted As SetAPBalancesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSuggestedPaymentCompleted As GetSuggestedPaymentCompletedEventHandler
        
        '''<remarks/>
        Public Event RequestUpdateCompleted As RequestUpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event TestRequestUpdateCompleted As TestRequestUpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateResponsesCompleted As UpdateResponsesCompletedEventHandler
        
        '''<remarks/>
        Public Event RequestUpdateWithAccountRefreshCompleted As RequestUpdateWithAccountRefreshCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld(ByVal Password As String) As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object() {Password})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal Password As String)
            Me.HelloWorldAsync(Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal Password As String, ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object() {Password}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestAPBalances", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestAPBalances(ByVal Password As String) As Boolean
            Dim results() As Object = Me.Invoke("TestAPBalances", New Object() {Password})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestAPBalancesAsync(ByVal Password As String)
            Me.TestAPBalancesAsync(Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestAPBalancesAsync(ByVal Password As String, ByVal userState As Object)
            If (Me.TestAPBalancesOperationCompleted Is Nothing) Then
                Me.TestAPBalancesOperationCompleted = AddressOf Me.OnTestAPBalancesOperationCompleted
            End If
            Me.InvokeAsync("TestAPBalances", New Object() {Password}, Me.TestAPBalancesOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestAPBalancesOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestAPBalancesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestAPBalancesCompleted(Me, New TestAPBalancesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetAPBalances", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SetAPBalances(ByVal Password As String, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal Balances() As APBalanceInfo) As Boolean
            Dim results() As Object = Me.Invoke("SetAPBalances", New Object() {Password, Balances})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SetAPBalancesAsync(ByVal Password As String, ByVal Balances() As APBalanceInfo)
            Me.SetAPBalancesAsync(Password, Balances, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetAPBalancesAsync(ByVal Password As String, ByVal Balances() As APBalanceInfo, ByVal userState As Object)
            If (Me.SetAPBalancesOperationCompleted Is Nothing) Then
                Me.SetAPBalancesOperationCompleted = AddressOf Me.OnSetAPBalancesOperationCompleted
            End If
            Me.InvokeAsync("SetAPBalances", New Object() {Password, Balances}, Me.SetAPBalancesOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetAPBalancesOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetAPBalancesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetAPBalancesCompleted(Me, New SetAPBalancesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSuggestedPayment", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSuggestedPayment(ByVal Password As String) As SPResponse
            Dim results() As Object = Me.Invoke("GetSuggestedPayment", New Object() {Password})
            Return CType(results(0),SPResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSuggestedPaymentAsync(ByVal Password As String)
            Me.GetSuggestedPaymentAsync(Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSuggestedPaymentAsync(ByVal Password As String, ByVal userState As Object)
            If (Me.GetSuggestedPaymentOperationCompleted Is Nothing) Then
                Me.GetSuggestedPaymentOperationCompleted = AddressOf Me.OnGetSuggestedPaymentOperationCompleted
            End If
            Me.InvokeAsync("GetSuggestedPayment", New Object() {Password}, Me.GetSuggestedPaymentOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSuggestedPaymentOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSuggestedPaymentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSuggestedPaymentCompleted(Me, New GetSuggestedPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestUpdate", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RequestUpdate(ByVal pword As String, ByVal Settings As SetupInfo) As DownloadResponse
            Dim results() As Object = Me.Invoke("RequestUpdate", New Object() {pword, Settings})
            Return CType(results(0),DownloadResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RequestUpdateAsync(ByVal pword As String, ByVal Settings As SetupInfo)
            Me.RequestUpdateAsync(pword, Settings, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RequestUpdateAsync(ByVal pword As String, ByVal Settings As SetupInfo, ByVal userState As Object)
            If (Me.RequestUpdateOperationCompleted Is Nothing) Then
                Me.RequestUpdateOperationCompleted = AddressOf Me.OnRequestUpdateOperationCompleted
            End If
            Me.InvokeAsync("RequestUpdate", New Object() {pword, Settings}, Me.RequestUpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnRequestUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.RequestUpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RequestUpdateCompleted(Me, New RequestUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestRequestUpdate", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestRequestUpdate(ByVal pword As String) As DownloadResponse
            Dim results() As Object = Me.Invoke("TestRequestUpdate", New Object() {pword})
            Return CType(results(0),DownloadResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestRequestUpdateAsync(ByVal pword As String)
            Me.TestRequestUpdateAsync(pword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestRequestUpdateAsync(ByVal pword As String, ByVal userState As Object)
            If (Me.TestRequestUpdateOperationCompleted Is Nothing) Then
                Me.TestRequestUpdateOperationCompleted = AddressOf Me.OnTestRequestUpdateOperationCompleted
            End If
            Me.InvokeAsync("TestRequestUpdate", New Object() {pword}, Me.TestRequestUpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestRequestUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestRequestUpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestRequestUpdateCompleted(Me, New TestRequestUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateResponses", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateResponses(ByVal pword As String, ByVal uResp As UpdateResponse)
            Me.Invoke("UpdateResponses", New Object() {pword, uResp})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateResponsesAsync(ByVal pword As String, ByVal uResp As UpdateResponse)
            Me.UpdateResponsesAsync(pword, uResp, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateResponsesAsync(ByVal pword As String, ByVal uResp As UpdateResponse, ByVal userState As Object)
            If (Me.UpdateResponsesOperationCompleted Is Nothing) Then
                Me.UpdateResponsesOperationCompleted = AddressOf Me.OnUpdateResponsesOperationCompleted
            End If
            Me.InvokeAsync("UpdateResponses", New Object() {pword, uResp}, Me.UpdateResponsesOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateResponsesOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateResponsesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateResponsesCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestUpdateWithAccountRefresh", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RequestUpdateWithAccountRefresh(ByVal pword As String, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal ccs() As ACUnit, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal accs() As ACUnit, ByVal settings As SetupInfo) As DownloadResponse
            Dim results() As Object = Me.Invoke("RequestUpdateWithAccountRefresh", New Object() {pword, ccs, accs, settings})
            Return CType(results(0),DownloadResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RequestUpdateWithAccountRefreshAsync(ByVal pword As String, ByVal ccs() As ACUnit, ByVal accs() As ACUnit, ByVal settings As SetupInfo)
            Me.RequestUpdateWithAccountRefreshAsync(pword, ccs, accs, settings, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RequestUpdateWithAccountRefreshAsync(ByVal pword As String, ByVal ccs() As ACUnit, ByVal accs() As ACUnit, ByVal settings As SetupInfo, ByVal userState As Object)
            If (Me.RequestUpdateWithAccountRefreshOperationCompleted Is Nothing) Then
                Me.RequestUpdateWithAccountRefreshOperationCompleted = AddressOf Me.OnRequestUpdateWithAccountRefreshOperationCompleted
            End If
            Me.InvokeAsync("RequestUpdateWithAccountRefresh", New Object() {pword, ccs, accs, settings}, Me.RequestUpdateWithAccountRefreshOperationCompleted, userState)
        End Sub
        
        Private Sub OnRequestUpdateWithAccountRefreshOperationCompleted(ByVal arg As Object)
            If (Not (Me.RequestUpdateWithAccountRefreshCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RequestUpdateWithAccountRefreshCompleted(Me, New RequestUpdateWithAccountRefreshCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class APBalanceInfo
        
        Private costCenterField As String
        
        Private expensesPayableField As Double
        
        Private spSalaryAdvField As Double
        
        Private previousSalaryField As Double
        
        Private accountBalanceField As Double
        
        Private advanceBalanceField As Double
        
        '''<remarks/>
        Public Property CostCenter() As String
            Get
                Return Me.costCenterField
            End Get
            Set
                Me.costCenterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExpensesPayable() As Double
            Get
                Return Me.expensesPayableField
            End Get
            Set
                Me.expensesPayableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SpSalaryAdv() As Double
            Get
                Return Me.spSalaryAdvField
            End Get
            Set
                Me.spSalaryAdvField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PreviousSalary() As Double
            Get
                Return Me.previousSalaryField
            End Get
            Set
                Me.previousSalaryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccountBalance() As Double
            Get
                Return Me.accountBalanceField
            End Get
            Set
                Me.accountBalanceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AdvanceBalance() As Double
            Get
                Return Me.advanceBalanceField
            End Get
            Set
                Me.advanceBalanceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ACUnit
        
        Private codeField As String
        
        Private nameField As String
        
        Private typeField As Integer
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As Integer
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StatusDescription
        
        Private statusField As String
        
        Private messageField As String
        
        Private rowIdField As Integer
        
        Private actualPeriodField As Integer
        
        Private actualYearField As Integer
        
        Private batchIdField As String
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RowId() As Integer
            Get
                Return Me.rowIdField
            End Get
            Set
                Me.rowIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActualPeriod() As Integer
            Get
                Return Me.actualPeriodField
            End Get
            Set
                Me.actualPeriodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActualYear() As Integer
            Get
                Return Me.actualYearField
            End Get
            Set
                Me.actualYearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchId() As String
            Get
                Return Me.batchIdField
            End Get
            Set
                Me.batchIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdateResponse
        
        Private tntStatusField As StatusDescription
        
        Private rmbsField() As StatusDescription
        
        Private budgetsField() As AP_Budget_Summary1
        
        '''<remarks/>
        Public Property TntStatus() As StatusDescription
            Get
                Return Me.tntStatusField
            End Get
            Set
                Me.tntStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Rmbs() As StatusDescription()
            Get
                Return Me.rmbsField
            End Get
            Set
                Me.rmbsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Budgets() As AP_Budget_Summary1()
            Get
                Return Me.budgetsField
            End Get
            Set
                Me.budgetsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AP_Budget_Summary1
        
        Private budgetSummaryIdField As Long
        
        Private accountField As String
        
        Private rcField As String
        
        Private p1Field As System.Nullable(Of Decimal)
        
        Private p2Field As System.Nullable(Of Decimal)
        
        Private p3Field As System.Nullable(Of Decimal)
        
        Private p4Field As System.Nullable(Of Decimal)
        
        Private p5Field As System.Nullable(Of Decimal)
        
        Private p6Field As System.Nullable(Of Decimal)
        
        Private p7Field As System.Nullable(Of Decimal)
        
        Private p8Field As System.Nullable(Of Decimal)
        
        Private p9Field As System.Nullable(Of Decimal)
        
        Private p10Field As System.Nullable(Of Decimal)
        
        Private p11Field As System.Nullable(Of Decimal)
        
        Private p12Field As System.Nullable(Of Decimal)
        
        Private fiscalYearField As Integer
        
        Private changedField As Boolean
        
        Private lastUpdatedField As System.Nullable(Of Date)
        
        Private portalidField As Integer
        
        Private errorField As System.Nullable(Of Boolean)
        
        Private errorMessageField As String
        
        '''<remarks/>
        Public Property BudgetSummaryId() As Long
            Get
                Return Me.budgetSummaryIdField
            End Get
            Set
                Me.budgetSummaryIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Account() As String
            Get
                Return Me.accountField
            End Get
            Set
                Me.accountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RC() As String
            Get
                Return Me.rcField
            End Get
            Set
                Me.rcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P1() As System.Nullable(Of Decimal)
            Get
                Return Me.p1Field
            End Get
            Set
                Me.p1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P2() As System.Nullable(Of Decimal)
            Get
                Return Me.p2Field
            End Get
            Set
                Me.p2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P3() As System.Nullable(Of Decimal)
            Get
                Return Me.p3Field
            End Get
            Set
                Me.p3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P4() As System.Nullable(Of Decimal)
            Get
                Return Me.p4Field
            End Get
            Set
                Me.p4Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P5() As System.Nullable(Of Decimal)
            Get
                Return Me.p5Field
            End Get
            Set
                Me.p5Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P6() As System.Nullable(Of Decimal)
            Get
                Return Me.p6Field
            End Get
            Set
                Me.p6Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P7() As System.Nullable(Of Decimal)
            Get
                Return Me.p7Field
            End Get
            Set
                Me.p7Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P8() As System.Nullable(Of Decimal)
            Get
                Return Me.p8Field
            End Get
            Set
                Me.p8Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P9() As System.Nullable(Of Decimal)
            Get
                Return Me.p9Field
            End Get
            Set
                Me.p9Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P10() As System.Nullable(Of Decimal)
            Get
                Return Me.p10Field
            End Get
            Set
                Me.p10Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P11() As System.Nullable(Of Decimal)
            Get
                Return Me.p11Field
            End Get
            Set
                Me.p11Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property P12() As System.Nullable(Of Decimal)
            Get
                Return Me.p12Field
            End Get
            Set
                Me.p12Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FiscalYear() As Integer
            Get
                Return Me.fiscalYearField
            End Get
            Set
                Me.fiscalYearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Changed() As Boolean
            Get
                Return Me.changedField
            End Get
            Set
                Me.changedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LastUpdated() As System.Nullable(Of Date)
            Get
                Return Me.lastUpdatedField
            End Get
            Set
                Me.lastUpdatedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Portalid() As Integer
            Get
                Return Me.portalidField
            End Get
            Set
                Me.portalidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [Error]() As System.Nullable(Of Boolean)
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Adv
        
        Private advanceIdField As Integer
        
        Private localAdvanceIdField As Integer
        
        Private amountField As Double
        
        Private reasonField As String
        
        Private userNameField As String
        
        Private userInitialsField As String
        
        Private staffNameField As String
        
        Private personalCostCenterField As String
        
        Private statusField As Integer
        
        Private approverNameField As String
        
        Private accountsNameField As String
        
        Private submittedDateField As Date
        
        Private approvedDateField As Date
        
        Private processDateField As Date
        
        Private periodField As Integer
        
        Private yearField As Integer
        
        Private origCurrencyField As String
        
        '''<remarks/>
        Public Property AdvanceId() As Integer
            Get
                Return Me.advanceIdField
            End Get
            Set
                Me.advanceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LocalAdvanceId() As Integer
            Get
                Return Me.localAdvanceIdField
            End Get
            Set
                Me.localAdvanceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Amount() As Double
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reason() As String
            Get
                Return Me.reasonField
            End Get
            Set
                Me.reasonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserInitials() As String
            Get
                Return Me.userInitialsField
            End Get
            Set
                Me.userInitialsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StaffName() As String
            Get
                Return Me.staffNameField
            End Get
            Set
                Me.staffNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonalCostCenter() As String
            Get
                Return Me.personalCostCenterField
            End Get
            Set
                Me.personalCostCenterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApproverName() As String
            Get
                Return Me.approverNameField
            End Get
            Set
                Me.approverNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccountsName() As String
            Get
                Return Me.accountsNameField
            End Get
            Set
                Me.accountsNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SubmittedDate() As Date
            Get
                Return Me.submittedDateField
            End Get
            Set
                Me.submittedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApprovedDate() As Date
            Get
                Return Me.approvedDateField
            End Get
            Set
                Me.approvedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProcessDate() As Date
            Get
                Return Me.processDateField
            End Get
            Set
                Me.processDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Period() As Integer
            Get
                Return Me.periodField
            End Get
            Set
                Me.periodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Year() As Integer
            Get
                Return Me.yearField
            End Get
            Set
                Me.yearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrigCurrency() As String
            Get
                Return Me.origCurrencyField
            End Get
            Set
                Me.origCurrencyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RmbLine
        
        Private rmbLineNoField As Integer
        
        Private rmbNoField As Integer
        
        Private lineTypeField As String
        
        Private accountCodeField As String
        
        Private costCenterField As String
        
        Private transDateField As Date
        
        Private commentField As String
        
        Private grossAmountField As Double
        
        Private taxableField As Boolean
        
        Private vATRateField As Boolean
        
        Private vATCodeField As String
        
        Private receiptField As Boolean
        
        Private receiptNoField As Integer
        
        Private mileageField As Integer
        
        Private mileageRateField As Integer
        
        Private analysisCodeField As String
        
        Private departmentField As Boolean
        
        Private vATField As Boolean
        
        '''<remarks/>
        Public Property RmbLineNo() As Integer
            Get
                Return Me.rmbLineNoField
            End Get
            Set
                Me.rmbLineNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RmbNo() As Integer
            Get
                Return Me.rmbNoField
            End Get
            Set
                Me.rmbNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LineType() As String
            Get
                Return Me.lineTypeField
            End Get
            Set
                Me.lineTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccountCode() As String
            Get
                Return Me.accountCodeField
            End Get
            Set
                Me.accountCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CostCenter() As String
            Get
                Return Me.costCenterField
            End Get
            Set
                Me.costCenterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransDate() As Date
            Get
                Return Me.transDateField
            End Get
            Set
                Me.transDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Comment() As String
            Get
                Return Me.commentField
            End Get
            Set
                Me.commentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GrossAmount() As Double
            Get
                Return Me.grossAmountField
            End Get
            Set
                Me.grossAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxable() As Boolean
            Get
                Return Me.taxableField
            End Get
            Set
                Me.taxableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VATRate() As Boolean
            Get
                Return Me.vATRateField
            End Get
            Set
                Me.vATRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VATCode() As String
            Get
                Return Me.vATCodeField
            End Get
            Set
                Me.vATCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Receipt() As Boolean
            Get
                Return Me.receiptField
            End Get
            Set
                Me.receiptField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceiptNo() As Integer
            Get
                Return Me.receiptNoField
            End Get
            Set
                Me.receiptNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mileage() As Integer
            Get
                Return Me.mileageField
            End Get
            Set
                Me.mileageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MileageRate() As Integer
            Get
                Return Me.mileageRateField
            End Get
            Set
                Me.mileageRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AnalysisCode() As String
            Get
                Return Me.analysisCodeField
            End Get
            Set
                Me.analysisCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As Boolean
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VAT() As Boolean
            Get
                Return Me.vATField
            End Get
            Set
                Me.vATField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Rmb
        
        Private rmbNoField As Integer
        
        Private userNameField As String
        
        Private userInitialsField As String
        
        Private staffNameField As String
        
        Private personalCostCenterField As String
        
        Private personalAccountCodeField As String
        
        Private statusField As Integer
        
        Private approverNameField As String
        
        Private accountsNameField As String
        
        Private submittedDateField As Date
        
        Private approvedDateField As Date
        
        Private processDateField As Date
        
        Private periodField As Integer
        
        Private yearField As Integer
        
        Private supplierCodeField As String
        
        Private advanceRequestField As Double
        
        Private errorDescField As String
        
        Private departmentField As Boolean
        
        Private rIDField As Integer
        
        Private linesField() As RmbLine
        
        '''<remarks/>
        Public Property RmbNo() As Integer
            Get
                Return Me.rmbNoField
            End Get
            Set
                Me.rmbNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserInitials() As String
            Get
                Return Me.userInitialsField
            End Get
            Set
                Me.userInitialsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StaffName() As String
            Get
                Return Me.staffNameField
            End Get
            Set
                Me.staffNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonalCostCenter() As String
            Get
                Return Me.personalCostCenterField
            End Get
            Set
                Me.personalCostCenterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonalAccountCode() As String
            Get
                Return Me.personalAccountCodeField
            End Get
            Set
                Me.personalAccountCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApproverName() As String
            Get
                Return Me.approverNameField
            End Get
            Set
                Me.approverNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccountsName() As String
            Get
                Return Me.accountsNameField
            End Get
            Set
                Me.accountsNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SubmittedDate() As Date
            Get
                Return Me.submittedDateField
            End Get
            Set
                Me.submittedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApprovedDate() As Date
            Get
                Return Me.approvedDateField
            End Get
            Set
                Me.approvedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProcessDate() As Date
            Get
                Return Me.processDateField
            End Get
            Set
                Me.processDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Period() As Integer
            Get
                Return Me.periodField
            End Get
            Set
                Me.periodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Year() As Integer
            Get
                Return Me.yearField
            End Get
            Set
                Me.yearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SupplierCode() As String
            Get
                Return Me.supplierCodeField
            End Get
            Set
                Me.supplierCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AdvanceRequest() As Double
            Get
                Return Me.advanceRequestField
            End Get
            Set
                Me.advanceRequestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDesc() As String
            Get
                Return Me.errorDescField
            End Get
            Set
                Me.errorDescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As Boolean
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RID() As Integer
            Get
                Return Me.rIDField
            End Get
            Set
                Me.rIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Lines() As RmbLine()
            Get
                Return Me.linesField
            End Get
            Set
                Me.linesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WebProfileAccount
        
        Private nameField As String
        
        Private costCenterField As String
        
        Private designationsField As String
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CostCenter() As String
            Get
                Return Me.costCenterField
            End Get
            Set
                Me.costCenterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Designations() As String
            Get
                Return Me.designationsField
            End Get
            Set
                Me.designationsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WebUser
        
        Private nameField As String
        
        Private gCXIDField As String
        
        Private gCXUserNameField As String
        
        Private userIdField As Integer
        
        Private accountsUserField As Boolean
        
        Private personalAccountsField() As WebProfileAccount
        
        Private teamAccountsField() As WebProfileAccount
        
        Private departmentAccountsField() As WebProfileAccount
        
        Private otherAccountsField() As WebProfileAccount
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GCXID() As String
            Get
                Return Me.gCXIDField
            End Get
            Set
                Me.gCXIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GCXUserName() As String
            Get
                Return Me.gCXUserNameField
            End Get
            Set
                Me.gCXUserNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserId() As Integer
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccountsUser() As Boolean
            Get
                Return Me.accountsUserField
            End Get
            Set
                Me.accountsUserField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property PersonalAccounts() As WebProfileAccount()
            Get
                Return Me.personalAccountsField
            End Get
            Set
                Me.personalAccountsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property TeamAccounts() As WebProfileAccount()
            Get
                Return Me.teamAccountsField
            End Get
            Set
                Me.teamAccountsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property DepartmentAccounts() As WebProfileAccount()
            Get
                Return Me.departmentAccountsField
            End Get
            Set
                Me.departmentAccountsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property OtherAccounts() As WebProfileAccount()
            Get
                Return Me.otherAccountsField
            End Get
            Set
                Me.otherAccountsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DownloadResponse
        
        Private statusField As String
        
        Private messageField As String
        
        Private valueField As Integer
        
        Private webUsersField() As WebUser
        
        Private rmbsField() As Rmb
        
        Private advancesField() As Adv
        
        Private changedBudgetsField() As AP_Budget_Summary1
        
        Private acctsReceivableField As String
        
        Private acctsPayableField As String
        
        Private taxableAcctsReceivableField As String
        
        Private controlAccountField As String
        
        Private aPIVersionField As String
        
        Private versionStatusField As String
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Integer
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property WebUsers() As WebUser()
            Get
                Return Me.webUsersField
            End Get
            Set
                Me.webUsersField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Rmbs() As Rmb()
            Get
                Return Me.rmbsField
            End Get
            Set
                Me.rmbsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Advances() As Adv()
            Get
                Return Me.advancesField
            End Get
            Set
                Me.advancesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ChangedBudgets() As AP_Budget_Summary1()
            Get
                Return Me.changedBudgetsField
            End Get
            Set
                Me.changedBudgetsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AcctsReceivable() As String
            Get
                Return Me.acctsReceivableField
            End Get
            Set
                Me.acctsReceivableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AcctsPayable() As String
            Get
                Return Me.acctsPayableField
            End Get
            Set
                Me.acctsPayableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TaxableAcctsReceivable() As String
            Get
                Return Me.taxableAcctsReceivableField
            End Get
            Set
                Me.taxableAcctsReceivableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ControlAccount() As String
            Get
                Return Me.controlAccountField
            End Get
            Set
                Me.controlAccountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property APIVersion() As String
            Get
                Return Me.aPIVersionField
            End Get
            Set
                Me.aPIVersionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VersionStatus() As String
            Get
                Return Me.versionStatusField
            End Get
            Set
                Me.versionStatusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetupInfo
        
        Private urlDataserverPortalField As String
        
        Private advSuffixField As String
        
        Private advPrefixField As String
        
        Private currencyCodeField As String
        
        Private companyIdField As String
        
        Private acDatalink_DatalinkIdField As String
        
        Private acDatalink_VersionField As String
        
        Private acDatalink_DataserverVersionField As String
        
        Private acDatalink_WindowsVersionField As String
        
        Private acDatalink_SQLVersionField As String
        
        Private acDatalink_TNT_InstallPathField As String
        
        Private acDatalink_acDatalink_ErrorField As String
        
        Private acDatalink_ActiveField As Boolean
        
        Private acDatalink_ComputerNameField As String
        
        Private acDatalink_PollDelayInSecondsField As Integer
        
        Private currentFiscalPeriodField As String
        
        Private changedBudgetsField() As AP_Budget_Summary1
        
        Private firstFiscalMonthField As Integer
        
        '''<remarks/>
        Public Property urlDataserverPortal() As String
            Get
                Return Me.urlDataserverPortalField
            End Get
            Set
                Me.urlDataserverPortalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AdvSuffix() As String
            Get
                Return Me.advSuffixField
            End Get
            Set
                Me.advSuffixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AdvPrefix() As String
            Get
                Return Me.advPrefixField
            End Get
            Set
                Me.advPrefixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CurrencyCode() As String
            Get
                Return Me.currencyCodeField
            End Get
            Set
                Me.currencyCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyId() As String
            Get
                Return Me.companyIdField
            End Get
            Set
                Me.companyIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acDatalink_DatalinkId() As String
            Get
                Return Me.acDatalink_DatalinkIdField
            End Get
            Set
                Me.acDatalink_DatalinkIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acDatalink_Version() As String
            Get
                Return Me.acDatalink_VersionField
            End Get
            Set
                Me.acDatalink_VersionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acDatalink_DataserverVersion() As String
            Get
                Return Me.acDatalink_DataserverVersionField
            End Get
            Set
                Me.acDatalink_DataserverVersionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acDatalink_WindowsVersion() As String
            Get
                Return Me.acDatalink_WindowsVersionField
            End Get
            Set
                Me.acDatalink_WindowsVersionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acDatalink_SQLVersion() As String
            Get
                Return Me.acDatalink_SQLVersionField
            End Get
            Set
                Me.acDatalink_SQLVersionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acDatalink_TNT_InstallPath() As String
            Get
                Return Me.acDatalink_TNT_InstallPathField
            End Get
            Set
                Me.acDatalink_TNT_InstallPathField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acDatalink_acDatalink_Error() As String
            Get
                Return Me.acDatalink_acDatalink_ErrorField
            End Get
            Set
                Me.acDatalink_acDatalink_ErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acDatalink_Active() As Boolean
            Get
                Return Me.acDatalink_ActiveField
            End Get
            Set
                Me.acDatalink_ActiveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acDatalink_ComputerName() As String
            Get
                Return Me.acDatalink_ComputerNameField
            End Get
            Set
                Me.acDatalink_ComputerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acDatalink_PollDelayInSeconds() As Integer
            Get
                Return Me.acDatalink_PollDelayInSecondsField
            End Get
            Set
                Me.acDatalink_PollDelayInSecondsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property currentFiscalPeriod() As String
            Get
                Return Me.currentFiscalPeriodField
            End Get
            Set
                Me.currentFiscalPeriodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property changedBudgets() As AP_Budget_Summary1()
            Get
                Return Me.changedBudgetsField
            End Get
            Set
                Me.changedBudgetsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstFiscalMonth() As Integer
            Get
                Return Me.firstFiscalMonthField
            End Get
            Set
                Me.firstFiscalMonthField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SuggestedPayment
        
        Private rcField As String
        
        Private nameField As String
        
        Private expPayableField As Double
        
        Private expTaxableField As Double
        
        Private salaryField As Double
        
        '''<remarks/>
        Public Property RC() As String
            Get
                Return Me.rcField
            End Get
            Set
                Me.rcField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExpPayable() As Double
            Get
                Return Me.expPayableField
            End Get
            Set
                Me.expPayableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExpTaxable() As Double
            Get
                Return Me.expTaxableField
            End Get
            Set
                Me.expTaxableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Salary() As Double
            Get
                Return Me.salaryField
            End Get
            Set
                Me.salaryField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SPResponse
        
        Private companyField As String
        
        Private controlField As String
        
        Private expensesPayableField As String
        
        Private payrolPayableField As String
        
        Private taxablePayableField As String
        
        Private salaryAccField As String
        
        Private formatField As Integer
        
        Private suggestedPaymentsField() As SuggestedPayment
        
        '''<remarks/>
        Public Property Company() As String
            Get
                Return Me.companyField
            End Get
            Set
                Me.companyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Control() As String
            Get
                Return Me.controlField
            End Get
            Set
                Me.controlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExpensesPayable() As String
            Get
                Return Me.expensesPayableField
            End Get
            Set
                Me.expensesPayableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PayrolPayable() As String
            Get
                Return Me.payrolPayableField
            End Get
            Set
                Me.payrolPayableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TaxablePayable() As String
            Get
                Return Me.taxablePayableField
            End Get
            Set
                Me.taxablePayableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SalaryAcc() As String
            Get
                Return Me.salaryAccField
            End Get
            Set
                Me.salaryAccField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Format() As Integer
            Get
                Return Me.formatField
            End Get
            Set
                Me.formatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property SuggestedPayments() As SuggestedPayment()
            Get
                Return Me.suggestedPaymentsField
            End Get
            Set
                Me.suggestedPaymentsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub TestAPBalancesCompletedEventHandler(ByVal sender As Object, ByVal e As TestAPBalancesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestAPBalancesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub SetAPBalancesCompletedEventHandler(ByVal sender As Object, ByVal e As SetAPBalancesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SetAPBalancesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub GetSuggestedPaymentCompletedEventHandler(ByVal sender As Object, ByVal e As GetSuggestedPaymentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSuggestedPaymentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SPResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SPResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RequestUpdateCompletedEventHandler(ByVal sender As Object, ByVal e As RequestUpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RequestUpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DownloadResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DownloadResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub TestRequestUpdateCompletedEventHandler(ByVal sender As Object, ByVal e As TestRequestUpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestRequestUpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DownloadResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DownloadResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub UpdateResponsesCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RequestUpdateWithAccountRefreshCompletedEventHandler(ByVal sender As Object, ByVal e As RequestUpdateWithAccountRefreshCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RequestUpdateWithAccountRefreshCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DownloadResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DownloadResponse)
            End Get
        End Property
    End Class
End Namespace
