'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
'
Namespace dynamicAgapeConnect
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DatatSyncSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DatatSync
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetupDataLinkOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RequestUpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateResponsesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RequestUpdateWithAccountRefreshOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.AgapeConnectDatapump.My.MySettings.Default.AgapeConnectDatapump_dynamicAgapeConnect_DatatSync
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event SetupDataLinkCompleted As SetupDataLinkCompletedEventHandler
        
        '''<remarks/>
        Public Event RequestUpdateCompleted As RequestUpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateResponsesCompleted As UpdateResponsesCompletedEventHandler
        
        '''<remarks/>
        Public Event RequestUpdateWithAccountRefreshCompleted As RequestUpdateWithAccountRefreshCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld(ByVal Password As String) As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object() {Password})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal Password As String)
            Me.HelloWorldAsync(Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal Password As String, ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object() {Password}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetupDataLink", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SetupDataLink(ByVal pword As String, ByVal config As SetupInfo, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal ccs() As ACUnit, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal accs() As ACUnit)
            Me.Invoke("SetupDataLink", New Object() {pword, config, ccs, accs})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetupDataLinkAsync(ByVal pword As String, ByVal config As SetupInfo, ByVal ccs() As ACUnit, ByVal accs() As ACUnit)
            Me.SetupDataLinkAsync(pword, config, ccs, accs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetupDataLinkAsync(ByVal pword As String, ByVal config As SetupInfo, ByVal ccs() As ACUnit, ByVal accs() As ACUnit, ByVal userState As Object)
            If (Me.SetupDataLinkOperationCompleted Is Nothing) Then
                Me.SetupDataLinkOperationCompleted = AddressOf Me.OnSetupDataLinkOperationCompleted
            End If
            Me.InvokeAsync("SetupDataLink", New Object() {pword, config, ccs, accs}, Me.SetupDataLinkOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetupDataLinkOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetupDataLinkCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetupDataLinkCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestUpdate", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RequestUpdate(ByVal pword As String) As DownloadResponse
            Dim results() As Object = Me.Invoke("RequestUpdate", New Object() {pword})
            Return CType(results(0),DownloadResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RequestUpdateAsync(ByVal pword As String)
            Me.RequestUpdateAsync(pword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RequestUpdateAsync(ByVal pword As String, ByVal userState As Object)
            If (Me.RequestUpdateOperationCompleted Is Nothing) Then
                Me.RequestUpdateOperationCompleted = AddressOf Me.OnRequestUpdateOperationCompleted
            End If
            Me.InvokeAsync("RequestUpdate", New Object() {pword}, Me.RequestUpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnRequestUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.RequestUpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RequestUpdateCompleted(Me, New RequestUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateResponses", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateResponses(ByVal pword As String, ByVal uResp As UpdateResponse)
            Me.Invoke("UpdateResponses", New Object() {pword, uResp})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateResponsesAsync(ByVal pword As String, ByVal uResp As UpdateResponse)
            Me.UpdateResponsesAsync(pword, uResp, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateResponsesAsync(ByVal pword As String, ByVal uResp As UpdateResponse, ByVal userState As Object)
            If (Me.UpdateResponsesOperationCompleted Is Nothing) Then
                Me.UpdateResponsesOperationCompleted = AddressOf Me.OnUpdateResponsesOperationCompleted
            End If
            Me.InvokeAsync("UpdateResponses", New Object() {pword, uResp}, Me.UpdateResponsesOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateResponsesOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateResponsesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateResponsesCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestUpdateWithAccountRefresh", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RequestUpdateWithAccountRefresh(ByVal pword As String, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal ccs() As ACUnit, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal accs() As ACUnit) As DownloadResponse
            Dim results() As Object = Me.Invoke("RequestUpdateWithAccountRefresh", New Object() {pword, ccs, accs})
            Return CType(results(0),DownloadResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RequestUpdateWithAccountRefreshAsync(ByVal pword As String, ByVal ccs() As ACUnit, ByVal accs() As ACUnit)
            Me.RequestUpdateWithAccountRefreshAsync(pword, ccs, accs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RequestUpdateWithAccountRefreshAsync(ByVal pword As String, ByVal ccs() As ACUnit, ByVal accs() As ACUnit, ByVal userState As Object)
            If (Me.RequestUpdateWithAccountRefreshOperationCompleted Is Nothing) Then
                Me.RequestUpdateWithAccountRefreshOperationCompleted = AddressOf Me.OnRequestUpdateWithAccountRefreshOperationCompleted
            End If
            Me.InvokeAsync("RequestUpdateWithAccountRefresh", New Object() {pword, ccs, accs}, Me.RequestUpdateWithAccountRefreshOperationCompleted, userState)
        End Sub
        
        Private Sub OnRequestUpdateWithAccountRefreshOperationCompleted(ByVal arg As Object)
            If (Not (Me.RequestUpdateWithAccountRefreshCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RequestUpdateWithAccountRefreshCompleted(Me, New RequestUpdateWithAccountRefreshCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetupInfo
        
        Private dsConnectionStringField As String
        
        Private solConnectionStringField As String
        
        Private urlAgapeConnectField As String
        
        Private urlDataserverPortalField As String
        
        Private advSuffixField As String
        
        Private advPrefixField As String
        
        Private currencyCodeField As String
        
        '''<remarks/>
        Public Property dsConnectionString() As String
            Get
                Return Me.dsConnectionStringField
            End Get
            Set
                Me.dsConnectionStringField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property solConnectionString() As String
            Get
                Return Me.solConnectionStringField
            End Get
            Set
                Me.solConnectionStringField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property urlAgapeConnect() As String
            Get
                Return Me.urlAgapeConnectField
            End Get
            Set
                Me.urlAgapeConnectField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property urlDataserverPortal() As String
            Get
                Return Me.urlDataserverPortalField
            End Get
            Set
                Me.urlDataserverPortalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AdvSuffix() As String
            Get
                Return Me.advSuffixField
            End Get
            Set
                Me.advSuffixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AdvPrefix() As String
            Get
                Return Me.advPrefixField
            End Get
            Set
                Me.advPrefixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CurrencyCode() As String
            Get
                Return Me.currencyCodeField
            End Get
            Set
                Me.currencyCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StatusDescription
        
        Private statusField As String
        
        Private messageField As String
        
        Private rowIdField As Integer
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RowId() As Integer
            Get
                Return Me.rowIdField
            End Get
            Set
                Me.rowIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdateResponse
        
        Private tntStatusField As StatusDescription
        
        Private rmbsField() As StatusDescription
        
        '''<remarks/>
        Public Property TntStatus() As StatusDescription
            Get
                Return Me.tntStatusField
            End Get
            Set
                Me.tntStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Rmbs() As StatusDescription()
            Get
                Return Me.rmbsField
            End Get
            Set
                Me.rmbsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RmbLine
        
        Private rmbLineNoField As Integer
        
        Private rmbNoField As Integer
        
        Private lineTypeField As String
        
        Private accountCodeField As String
        
        Private costCenterField As String
        
        Private transDateField As Date
        
        Private commentField As String
        
        Private grossAmountField As Double
        
        Private taxableField As Boolean
        
        Private vATRateField As Boolean
        
        Private vATCodeField As String
        
        Private receiptField As Boolean
        
        Private receiptNoField As Integer
        
        Private mileageField As Integer
        
        Private mileageRateField As Integer
        
        Private analysisCodeField As String
        
        Private departmentField As Boolean
        
        Private vATField As Boolean
        
        '''<remarks/>
        Public Property RmbLineNo() As Integer
            Get
                Return Me.rmbLineNoField
            End Get
            Set
                Me.rmbLineNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RmbNo() As Integer
            Get
                Return Me.rmbNoField
            End Get
            Set
                Me.rmbNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LineType() As String
            Get
                Return Me.lineTypeField
            End Get
            Set
                Me.lineTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccountCode() As String
            Get
                Return Me.accountCodeField
            End Get
            Set
                Me.accountCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CostCenter() As String
            Get
                Return Me.costCenterField
            End Get
            Set
                Me.costCenterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransDate() As Date
            Get
                Return Me.transDateField
            End Get
            Set
                Me.transDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Comment() As String
            Get
                Return Me.commentField
            End Get
            Set
                Me.commentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GrossAmount() As Double
            Get
                Return Me.grossAmountField
            End Get
            Set
                Me.grossAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxable() As Boolean
            Get
                Return Me.taxableField
            End Get
            Set
                Me.taxableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VATRate() As Boolean
            Get
                Return Me.vATRateField
            End Get
            Set
                Me.vATRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VATCode() As String
            Get
                Return Me.vATCodeField
            End Get
            Set
                Me.vATCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Receipt() As Boolean
            Get
                Return Me.receiptField
            End Get
            Set
                Me.receiptField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceiptNo() As Integer
            Get
                Return Me.receiptNoField
            End Get
            Set
                Me.receiptNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mileage() As Integer
            Get
                Return Me.mileageField
            End Get
            Set
                Me.mileageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MileageRate() As Integer
            Get
                Return Me.mileageRateField
            End Get
            Set
                Me.mileageRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AnalysisCode() As String
            Get
                Return Me.analysisCodeField
            End Get
            Set
                Me.analysisCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As Boolean
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VAT() As Boolean
            Get
                Return Me.vATField
            End Get
            Set
                Me.vATField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Rmb
        
        Private rmbNoField As Integer
        
        Private userNameField As String
        
        Private userInitialsField As String
        
        Private staffNameField As String
        
        Private personalCostCenterField As String
        
        Private statusField As Integer
        
        Private approverNameField As String
        
        Private accountsNameField As String
        
        Private submittedDateField As Date
        
        Private approvedDateField As Date
        
        Private processDateField As Date
        
        Private periodField As Integer
        
        Private yearField As Integer
        
        Private supplierCodeField As String
        
        Private advanceRequestField As Double
        
        Private errorDescField As String
        
        Private departmentField As Boolean
        
        Private rIDField As Integer
        
        Private linesField() As RmbLine
        
        '''<remarks/>
        Public Property RmbNo() As Integer
            Get
                Return Me.rmbNoField
            End Get
            Set
                Me.rmbNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserInitials() As String
            Get
                Return Me.userInitialsField
            End Get
            Set
                Me.userInitialsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StaffName() As String
            Get
                Return Me.staffNameField
            End Get
            Set
                Me.staffNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonalCostCenter() As String
            Get
                Return Me.personalCostCenterField
            End Get
            Set
                Me.personalCostCenterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApproverName() As String
            Get
                Return Me.approverNameField
            End Get
            Set
                Me.approverNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccountsName() As String
            Get
                Return Me.accountsNameField
            End Get
            Set
                Me.accountsNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SubmittedDate() As Date
            Get
                Return Me.submittedDateField
            End Get
            Set
                Me.submittedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApprovedDate() As Date
            Get
                Return Me.approvedDateField
            End Get
            Set
                Me.approvedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProcessDate() As Date
            Get
                Return Me.processDateField
            End Get
            Set
                Me.processDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Period() As Integer
            Get
                Return Me.periodField
            End Get
            Set
                Me.periodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Year() As Integer
            Get
                Return Me.yearField
            End Get
            Set
                Me.yearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SupplierCode() As String
            Get
                Return Me.supplierCodeField
            End Get
            Set
                Me.supplierCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AdvanceRequest() As Double
            Get
                Return Me.advanceRequestField
            End Get
            Set
                Me.advanceRequestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDesc() As String
            Get
                Return Me.errorDescField
            End Get
            Set
                Me.errorDescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As Boolean
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RID() As Integer
            Get
                Return Me.rIDField
            End Get
            Set
                Me.rIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Lines() As RmbLine()
            Get
                Return Me.linesField
            End Get
            Set
                Me.linesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WebProfileAccount
        
        Private nameField As String
        
        Private costCenterField As String
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CostCenter() As String
            Get
                Return Me.costCenterField
            End Get
            Set
                Me.costCenterField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WebUser
        
        Private nameField As String
        
        Private gCXIDField As String
        
        Private gCXUserNameField As String
        
        Private userIdField As Integer
        
        Private personalAccountsField() As WebProfileAccount
        
        Private teamAccountsField() As WebProfileAccount
        
        Private departmentAccountsField() As WebProfileAccount
        
        Private otherAccountsField() As WebProfileAccount
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GCXID() As String
            Get
                Return Me.gCXIDField
            End Get
            Set
                Me.gCXIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GCXUserName() As String
            Get
                Return Me.gCXUserNameField
            End Get
            Set
                Me.gCXUserNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserId() As Integer
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property PersonalAccounts() As WebProfileAccount()
            Get
                Return Me.personalAccountsField
            End Get
            Set
                Me.personalAccountsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property TeamAccounts() As WebProfileAccount()
            Get
                Return Me.teamAccountsField
            End Get
            Set
                Me.teamAccountsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property DepartmentAccounts() As WebProfileAccount()
            Get
                Return Me.departmentAccountsField
            End Get
            Set
                Me.departmentAccountsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property OtherAccounts() As WebProfileAccount()
            Get
                Return Me.otherAccountsField
            End Get
            Set
                Me.otherAccountsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DownloadResponse
        
        Private statusField As String
        
        Private messageField As String
        
        Private valueField As Integer
        
        Private webUsersField() As WebUser
        
        Private rmbsField() As Rmb
        
        Private acctsReceivableField As String
        
        Private acctsPayableField As String
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Integer
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property WebUsers() As WebUser()
            Get
                Return Me.webUsersField
            End Get
            Set
                Me.webUsersField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Rmbs() As Rmb()
            Get
                Return Me.rmbsField
            End Get
            Set
                Me.rmbsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AcctsReceivable() As String
            Get
                Return Me.acctsReceivableField
            End Get
            Set
                Me.acctsReceivableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AcctsPayable() As String
            Get
                Return Me.acctsPayableField
            End Get
            Set
                Me.acctsPayableField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ACUnit
        
        Private codeField As String
        
        Private nameField As String
        
        Private typeField As Integer
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As Integer
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub SetupDataLinkCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub RequestUpdateCompletedEventHandler(ByVal sender As Object, ByVal e As RequestUpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RequestUpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DownloadResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DownloadResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub UpdateResponsesCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub RequestUpdateWithAccountRefreshCompletedEventHandler(ByVal sender As Object, ByVal e As RequestUpdateWithAccountRefreshCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RequestUpdateWithAccountRefreshCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DownloadResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DownloadResponse)
            End Get
        End Property
    End Class
End Namespace
